name: Bug Report
description: Report incorrect behavior in the pycaret library
title: "BUG: "
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: pycaret version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.
          required: true
        - label: >
            I have confirmed this bug exists on the main branch of pandas.
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example. If using a data source other than one that is inbuilt in pycaret,
        please prvide the dataset so that the problem can be recreated by the person debugging. Providing incomplete
        information will cause delays in response and resolution.
      placeholder: >
        from pycaret.datasets import get_data
        
        from pycaret.classification import setup
        
        data = get_data('diabetes')
        s = setup(data, target = 'Class variable')

        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: >
        Please paste the output of ``from pycaret import show_version; show_versions()``
        If this does not work, try this instead ``import pycaret; pycaret.__version__``
      value: >
        <details>

        Replace this line with the output of the version code above.

        </details>
    validations:
      required: true
